# Generated by Django 5.2.9 on 2026-01-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FutsalField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("location", models.CharField(max_length=255)),
                (
                    "price_per_hour",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("open_time", models.TimeField(default="07:00")),
                ("close_time", models.TimeField(default="00:00")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
